## Merging the Amazon Purchase Data and Survey Data and Dataset Cleaning

### Merging the Data

In [11]:
# Creating the amazon purchase dataframe as before

import pandas as pd

amazon1 = pd.read_csv('/workspaces/group-project-bas-team/data/AmazonData1.csv')
amazon2 = pd.read_csv('/workspaces/group-project-bas-team/data/AmazonData2.csv')

amazon_data = [amazon1, amazon2]

amazon = pd.concat(amazon_data)

In [12]:
# reading in the survey data

survey = pd.read_csv('/workspaces/group-project-bas-team/data/survey.csv')

In [13]:
# Merging the Amazon purchase data and survey data on the "Survey ResponseID" column
# Merge type should not matter since we confirmed no missing values in this column of both dataframes, but we will use "outer" just in case

data = pd.merge(amazon, survey, on='Survey ResponseID', how='outer')
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1050756 entries, 0 to 1050755
Data columns (total 30 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   Order Date                  1048575 non-null  str
 1   Purchase Price Per Unit     1048575 non-null  float64
 2   Quantity                    1048575 non-null  float64
 3   Shipping Address State      997480 non-null   str
 4   Title                       997060 non-null   str
 5   ASIN/ISBN (Product Code)    1047967 non-null  str
 6   Category                    997766 non-null   str
 7   Survey ResponseID           1050756 non-null  str
 8   Q-demos-age                 1050756 non-null  str
 9   Q-demos-hispanic            1050756 non-null  str
 10  Q-demos-race                1050756 non-null  str
 11  Q-demos-education           1050756 non-null  str
 12  Q-demos-income              1050756 non-null  str
 13  Q-demos-gender              1050756 non-null  str
 14  Q-sexual-orientation        1050756 non-null  str
 15  Q-demos-state               1050756 non-null  str
 16  Q-amazon-use-howmany        1050756 non-null  str
 17  Q-amazon-use-hh-size        1050756 non-null  str
 18  Q-amazon-use-how-oft        1050756 non-null  str
 19  Q-substance-use-cigarettes  1050756 non-null  str
 20  Q-substance-use-marijuana   1050756 non-null  str
 21  Q-substance-use-alcohol     1050756 non-null  str
 22  Q-personal-diabetes         1050756 non-null  str
 23  Q-personal-wheelchair       1050756 non-null  str
 24  Q-life-changes              338505 non-null   str
 25  Q-sell-YOUR-data            1050756 non-null  str
 26  Q-sell-consumer-data        1050756 non-null  str
 27  Q-small-biz-use             1050756 non-null  str
 28  Q-census-use                1050756 non-null  str
 29  Q-research-society          1050756 non-null  str
dtypes: float64(2), str(28)
memory usage: 240.5 MB

### Data Cleaning

In [14]:
data[data[['Order Date', 'Purchase Price Per Unit', 'Quantity', 
           'Shipping Address State', 'Title', 'ASIN/ISBN (Product Code)', 'Category']].isna().all(axis=1)]
# Finding rows where all amazon data (minus survey response ID) is null
# These are presumably rows entries for people who responded to the survey, but have not purchased anything on amazon during the data collection period
# Since we do not have purchase data for these instances, they will be removed from our data

,Order Date,Purchase Price Per Unit,Quantity,Shipping Address State,Title,ASIN/ISBN (Product Code),Category,Survey ResponseID,Q-demos-age,Q-demos-hispanic,...,Q-substance-use-marijuana,Q-substance-use-alcohol,Q-personal-diabetes,Q-personal-wheelchair,Q-life-changes,Q-sell-YOUR-data,Q-sell-consumer-data,Q-small-biz-use,Q-census-use,Q-research-society
1048575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R_3Gr02vFv0h79T4p,25 - 34 years,No,...,No,No,No,No,NaN,No,No,No,No,Yes
1048576,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R_3GrjtiJ9M19hViM,25 - 34 years,No,...,I stopped in the recent past,Yes,No,No,NaN,No,No,I don't know,No,Yes
1048577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R_3Gvq8BkHNwpHB6L,25 - 34 years,No,...,No,No,No,No,NaN,No,No,Yes,I don't know,Yes
1048578,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R_3Gvz2XC7yM8Jb83,35 - 44 years,No,...,No,Yes,No,No,NaN,Yes if I get part of the profit,Yes if consumers get part of the profit,Yes,I don't know,Yes
1048579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R_3GwCCWUgtO6KqAH,35 - 44 years,No,...,No,Yes,No,No,Moved place of residence,I don't know,I don't know,No,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1050751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R_zd4E1BgAdaM2761,25 - 34 years,No,...,Yes,Yes,No,No,NaN,Yes if I get part of the profit,No,Yes,Yes,Yes
1050752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R_zdLOP8JD2pe1brj,18 - 24 years,No,...,Yes,Yes,No,No,"Lost a job ,Moved place of residence",Yes if I get part of the profit,Yes if consumers get part of the profit,No,Yes,Yes
1050753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R_zdQYFhfeqyBd2dH,25 - 34 years,No,...,Yes,No,No,No,Became pregnant,No,Yes if consumers get part of the profit,I don't know,I don't know,Yes
1050754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R_zfnsck2ZatnGtY5,25 - 34 years,No,...,Yes,Yes,No,No,NaN,No,No,Yes,I don't know,Yes
1050755,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R_zfqnsBzlOAKibzb,35 - 44 years,No,...,No,No,No,Yes,NaN,No,No,Yes,I don't know,Yes

In [15]:
data = data[data[['Order Date', 'Purchase Price Per Unit',
                  'Quantity', 'Shipping Address State',
                  'Title', 'ASIN/ISBN (Product Code)', 'Category']].isna().all(axis=1) == False]

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 30 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   Order Date                  1048575 non-null  str
 1   Purchase Price Per Unit     1048575 non-null  float64
 2   Quantity                    1048575 non-null  float64
 3   Shipping Address State      997480 non-null   str
 4   Title                       997060 non-null   str
 5   ASIN/ISBN (Product Code)    1047967 non-null  str
 6   Category                    997766 non-null   str
 7   Survey ResponseID           1048575 non-null  str
 8   Q-demos-age                 1048575 non-null  str
 9   Q-demos-hispanic            1048575 non-null  str
 10  Q-demos-race                1048575 non-null  str
 11  Q-demos-education           1048575 non-null  str
 12  Q-demos-income              1048575 non-null  str
 13  Q-demos-gender              1048575 non-null  str
 14  Q-sexual-orientation        1048575 non-null  str
 15  Q-demos-state               1048575 non-null  str
 16  Q-amazon-use-howmany        1048575 non-null  str
 17  Q-amazon-use-hh-size        1048575 non-null  str
 18  Q-amazon-use-how-oft        1048575 non-null  str
 19  Q-substance-use-cigarettes  1048575 non-null  str
 20  Q-substance-use-marijuana   1048575 non-null  str
 21  Q-substance-use-alcohol     1048575 non-null  str
 22  Q-personal-diabetes         1048575 non-null  str
 23  Q-personal-wheelchair       1048575 non-null  str
 24  Q-life-changes              337784 non-null   str
 25  Q-sell-YOUR-data            1048575 non-null  str
 26  Q-sell-consumer-data        1048575 non-null  str
 27  Q-small-biz-use             1048575 non-null  str
 28  Q-census-use                1048575 non-null  str
 29  Q-research-society          1048575 non-null  str
dtypes: float64(2), str(28)
memory usage: 240.0 MB

In [16]:
# Attempting to identify Title and Category information from matching ASIN/ISBN codes
data[data['Title'].isna()]

,Order Date,Purchase Price Per Unit,Quantity,Shipping Address State,Title,ASIN/ISBN (Product Code),Category,Survey ResponseID,Q-demos-age,Q-demos-hispanic,...,Q-substance-use-marijuana,Q-substance-use-alcohol,Q-personal-diabetes,Q-personal-wheelchair,Q-life-changes,Q-sell-YOUR-data,Q-sell-consumer-data,Q-small-biz-use,Q-census-use,Q-research-society
2,12/24/2018,8.99,1.0,NJ,NaN,B078JZTFN3,NaN,R_01vNIayewjIIKMF,35 - 44 years,Yes,...,No,No,No,No,NaN,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
9,4/23/2019,24.69,1.0,NJ,NaN,B06XKNWJN2,NaN,R_01vNIayewjIIKMF,35 - 44 years,Yes,...,No,No,No,No,NaN,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
36,10/7/2019,11.94,1.0,NJ,NaN,B07CZ6JCZS,NaN,R_01vNIayewjIIKMF,35 - 44 years,Yes,...,No,No,No,No,NaN,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
41,10/18/2019,14.26,1.0,NJ,NaN,B00KVM2SSO,NaN,R_01vNIayewjIIKMF,35 - 44 years,Yes,...,No,No,No,No,NaN,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
59,12/22/2019,14.33,1.0,NJ,NaN,B00KVM2SSO,NaN,R_01vNIayewjIIKMF,35 - 44 years,Yes,...,No,No,No,No,NaN,Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048440,4/27/2022,29.74,1.0,MA,NaN,B08KF3GWGY,NaN,R_3GqD1hXu6eSqH31,35 - 44 years,No,...,No,Yes,No,No,"Divorce,Moved place of residence",Yes if I get part of the profit,Yes if consumers get part of the profit,No,No,No
1048531,2/9/2018,2.48,1.0,FL,NaN,B079GRZYQQ,NaN,R_3GqfePl8gH1VWP1,35 - 44 years,No,...,Yes,No,No,No,"Lost a job ,Divorce",Yes if I get part of the profit,Yes if consumers get part of the profit,Yes,I don't know,Yes
1048536,2/21/2018,11.45,1.0,FL,NaN,B008JFIJRY,NaN,R_3GqfePl8gH1VWP1,35 - 44 years,No,...,Yes,No,No,No,"Lost a job ,Divorce",Yes if I get part of the profit,Yes if consumers get part of the profit,Yes,I don't know,Yes
1048553,4/27/2018,9.99,1.0,FL,NaN,B074XB3XL5,NaN,R_3GqfePl8gH1VWP1,35 - 44 years,No,...,Yes,No,No,No,"Lost a job ,Divorce",Yes if I get part of the profit,Yes if consumers get part of the profit,Yes,I don't know,Yes
1048554,5/16/2018,56.24,1.0,FL,NaN,B07BV4PSW3,NaN,R_3GqfePl8gH1VWP1,35 - 44 years,No,...,Yes,No,No,No,"Lost a job ,Divorce",Yes if I get part of the profit,Yes if consumers get part of the profit,Yes,I don't know,Yes

In [17]:
codes = data[['ASIN/ISBN (Product Code)', 'Title']].drop_duplicates().dropna()

In [18]:
codes_dict = codes.set_index('ASIN/ISBN (Product Code)')['Title'].to_dict()
codes_dict

{'B0143RTB1E': 'SanDisk Ultra 16GB Class 10 SDHC UHS-I Memory Card up to 80MB/s (SDSDUNC-016G-GN6IN)',
 'B01MA1MJ6H': 'Betron BS10 Earphones Wired Headphones in Ear Noise Isolating Earbuds with Microphone and Volume Control Powerful Bass Driven Sound, 12mm Large Drivers, Ergonomic Design',
 'B06XWF9HML': 'Perfecto Stainless Steel Shaving Bowl. Durable Metal Mug For Shaving Soap & Cream. Perfect Addition To Your Wet Shaving Kit. Double Layer Smooth Shave Unbreakable Mug With Heat Insulation',
 'B00837ZOI0': 'Proraso Shaving Cream for Men',
 'B01GFB2E9M': 'Micro USB Cable Android Charger - Syncwire [2-Pack 6.6ft] Super-Durable Nylon Braided Fast Sync&Charging Cord for Samsung Galaxy S7 Edge/S7/S6, Kindle, HTC, LG, Sony, Xbox One, PS4 - Space Grey',
 'B00NH13S44': 'Amazon Basics USB 2.0 Charger Cable - A-Male to Mini-B Cord - 3 Feet (0.9 Meters) for Personal Computer.',
 'B077H6L7T9': 'Fire HD 8 Tablet (8" HD Display, 32 GB, without Special Offers) - Black (Previous Generation - 8th)',
 'B07L84ZZXC': "Men's Leather Belt, Ratchet Dress Belt with Automatic Buckle for Father's Day Gift by WERFORU",
 'B07CG71KQ1': 'UGREEN Tablet Stand Holder Adjustable Portable Desktop Holder Dock Office Desk Accessories Compatible for iPad 10.2 iPad Pro 11 Inch iPad 9.7 iPad Mini 5 4 3 2 iPad Air iPhone 14 13 12 Black',
 'B079GFF4HZ': 'Betron B25 in-Ear Headphones Earphones with Microphone and Volume Controller, Noise Isolating Earbud Tips, 3.5mm Head Phone Jack',
 'B01M0Q84BR': 'NEW Norpro Instant Immersion Heater Coffee/Tea/Soup Electric Water Portable Reheater',
 'B073JYC4XM': 'SanDisk 128GB Ultra MicroSDXC UHS-I Memory Card with Adapter - 100MB/s, C10, U1, Full HD, A1, Micro SD Card - SDSQUAR-128G-GN6MA',
 'B00I7DT454': 'Slippery Stuff, 16 oz Gel, Clear, Pound , Unscented, 1 Count (LU031)',
 'B0043T7FXE': 'Logitech M570 Wireless Trackball Mouse â€“ Ergonomic Design with Sculpted Right-Hand Shape, Compatible with Apple Mac / Microsoft, USB Unifying Receiver, Dark Gray (Discontinued by Manufacturer)',
 'B01M2V05RE': 'Betron BS10 Earphones Wired in Ear Earbud Headphones Strong Bass Noise Isolating Ear Buds 3.5mm Jack Tangle-Free Cord Compatible with Tablet Laptop iPhone iPad Smartphones (Black)',
 'B07BCZMBNR': 'TUDIA Motorola Moto G6 Case, Full-Matte Lightweight [Arch S] TPU Bumper Shock Absorption Cover for Motorola Moto G6 (Black)',
 'B075CMYT43': 'WOWMAX Triangular Reading Pillow Large Bolster Headboard Backrest Positioning Support Wedge Pillow, Pillow for Day Bed Bunk Bed with Removable Cover Jean Blue 39x8x20inch',
 'B01MZ956SX': 'KROSER Laptop Bag 15.6 Inch Briefcase Shoulder Bag Water Repellent Laptop Bag Satchel Tablet Bussiness Carrying Handbag Laptop Sleeve for Women and Men-Charcoal Black',
 'B07JCJP1DK': "Gildan Men's Underwear Boxer Briefs, Multipack",
 'B07JD5B8SP': "Gildan Men's Boxer Briefs, Multipack",
 'B071XGLB1S': 'Tape Measure for Body Measuring Tape for Body Measurements Tape Tailor Clothing',
 'B071ZBV7DY': 'Poetic SlimFolio case for All-New Amazon Fire HD 8 Tablet (7th and 8th Generation, 2017 and 2018 Release) - Slim Leather Stand Folio Smart Cover Case with Auto Wake/Sleep - Black',
 'B07D5V2ZXD': 'WD 8TB Elements Desktop External Hard Drive, USB 3.0 external hard drive for plug-and-play storage - WDBWLG0080HBK-NESN',
 'B01BNEWDFQ': 'Colgate Cavity Protection Toothpaste with Fluoride, Great Regular Flavor, 6 Ounce (Pack of 6)',
 'B01NBYY28W': 'Scott 1000 Sheets Per Roll Toilet Paper, 27 Rolls, Bath Tissue',
 'B019FGCOW6': 'Crest Scope Outlast Mouthwash, Long Lasting Peppermint, 1 L',
 'B072JYDQ7N': 'Anker Powerline II USB-C to USB-C 3.1 Gen 2 Cable (3ft) with Power Delivery, for Apple MacBook, Huawei Matebook, iPad Pro 2020, Chromebook, Pixel, Switch, and More Type-C Devices/Laptops',
 'B00MUJU33S': 'Kingsdun 12Pcs Magnetic Torx Screwdriver Sets with T3 T4 T5 T6 T7 T8 T10 Star Screwdrivers, Stainless Steel Tweezers & Philip Slotted Screwdrivers for Phone/Mac/Camera/Computer Repairing',
 'B07RTN4C77': 'Best Buy Gift Cards - Email Delivery',
 'B01IQ00B04': 'BetterBody Foods Refined Avocado Oil, Non-GMO Cooking Oil, Kosher, Keto and Paleo Diet Friendly, for High-Heat Cooking, Frying, Baking, 100% Pure Avocado Oil, 500 mL, 16.9 Fl Oz',
 'B017ALC6GW': 'Pompeian USDA Organic Robust Extra Virgin Olive Oil, First Cold Pressed, Full-Bodied Flavor, Perfect for Salad Dressings & Marinades, 24 FL. OZ.',
 'B0741FV7ZV': '$15/Month Mint Mobile Phone Plan | 4GB of 5G â€¢ 4G LTE Data + Unlimited Talk & Text for 3 Months (3-in-1 SIM Card)',
 'B006MIPW70': 'ZINUS SmartBase Tool-Free Assembly Mattress Foundation / 14 Inch Metal Platform Bed Frame / No Box Spring Needed / Sturdy Steel Frame / Underbed Storage, Black, Twin, Regular',
 'B01LZKYNIM': 'McCormick Black Peppercorn Grinder, 2.5 oz',
 'B00NC8QEKM': 'Dietz & Watson deli Sliced Black Forest Smoked Ham, 0.5 lbs',
 'B0011EKWBQ': 'Kerrygold Pure Irish Butter, Salted, 8 oz',
 'B00NC882CA': 'Dietz & Watson Sliced Mozzarella Cheese, 0.5 lbs',
 'B00B9GUZP4': 'Jack Links Premium Cuts Beef Steak, Original, Strips -Great Protein Snack with 11g of Protein and 1g of Carbs Per Serving, Made with Beef, 1 Ounce (Pack of 12)',
 'B000QD9C8M': 'Wet Naturals Beautifully Bare - 3.3 fl oz',
 'B01LZ5SB6U': "Tracy's Dog Male Masturbators Pocket Pussy Realistic Stroker Lifelike Vaginal Oral Sex Toys for Man Masturbation (Flesh)",
 'B072HRDM55': 'SAMSUNG (MB-ME256GA/AM) 256GB 100MB/s (U3) MicroSDXC EVO Select Memory Card with Full-Size Adapter',
 'B07DGQ4QR3': 'LubeLife Water-Based Personal Lubricant, Lube for Men, Women and Couples, Non-Staining, 12 Fl Oz',
 'B06XWZWYVP': 'SAMSUNG (MB-ME128GA/AM) 128GB 100MB/s (U3) MicroSDXC EVO Select Memory Card with Full-Size Adapter',
 'B07H8GC6WL': "Tracy's Dog Male Masturbators Cup Adult Sex Toys Realistic Textured Pocket Vagina Pussy Man Masturbation Stroker",
 'B01DVLP2UW': "Tracy's Dog Male Masturbator, Deep Throat Blow Job Stroker Realistic Mouth with Teeth and Tongue, Close-Ended Pocket Pal Oral Adult Sex Toys for Man Masturbation",
 'B075SN1MY9': '#LubeLife Water-Based Personal Lubricant, Lube for Men, Women and Couples, Non-Staining, 8 Fl Oz',
 'B07GKKSXBS': 'TOYMYTOY A5 Plastic Poly Zipper Envelope File Folder Bags File Pockets,24x18cm,40Pcs (Red Yellow Blue Green)',
 'B001U0PA7M': 'Lewis N. Portable Immersion Water Heater + Electric Kettle Alternative for Coffee, Tea + Hot Chocolate, Camping, Travel + Office w/Travel Adapter, White, 120/240v',
 'B00GAC1D2G': '$10 -PlayStation Store Gift Card [Digital Code]',
 'B083V5CFMP': 'Betron ZH50 Earbuds, Wireless Bluetooth Earbud Headphones with Mic Noise Isolating TWS Earphones',
 'B07F42TGQF': 'USB Type C Cable, Syncwire [2 Pack, 6Ft] USB 3.0 Fast Charging & Sync Nylon Braided USB A to USB-C Charger Cord for Samsung Galaxy S10/S9/S8 Plus/Note 9/8, Nintendo Switch, LG V30, V20, G6, G5',
 'B072PW59TZ': 'Amazon Basics Carrying Case for Nintendo Switch - Black',
 'B07VDDDPKY': 'UGREEN SD Card Reader USB 3.0 Memory Card Reader Adapter Aluminum Dual Slot for SD SDXC SDHC MMC RS-MMC Micro SD TF Micro SDXC Micro SDHC UHS-I for Mac Windows Linux Chromebook PS4 PC',
 'B0866C659Q': 'JLab Go Air True Wireless Bluetooth Earbuds + Charging Case | Black | Dual Connect | IP44 Sweat Resistance | Bluetooth 5.0 Connection | 3 EQ Sound Settings Signature, Balanced, Bass Boost',
 'B00IX1I3G6': 'Amazon.com Gift Card Balance Reload',
 'B07R6RR3RQ': 'HOMEST 2 Pack Large Nylon Laundry Bag, Machine Washable Large Dirty Clothes Organizer, Easy Fit a Laundry Hamper or Basket, Can Carry Up to 4 Loads of Laundry, Black and Grey',
 'B015PPQXY6': 'Ethernet Cable, VANDESAIL CAT7 Network Cable RJ45 High Speed STP LAN Cord Gigabit 10/100/1000Mbit/s Gold Plated Lead',
 'B08GQF2SGQ': 'Seagate One Touch 2TB External Hard Drive HDD â€“ Black USB 3.0 for PC Laptop and Mac, 1 Year MylioCreate, 4 Months Adobe Creative Cloud Photography Plan (STKB2000412)',
 'B07TJVXNHX': 'Sleep Earphone for Side Sleeper,Ultra Soft Comfortable Noise Reduction Sleep Headphones Earplugs Earbuds with Mic for Insomnia, Light Sleeper, Air Travel, Meditation,Yoga, Relaxation Rest',
 'B088LW4JKR': 'Tribit Wireless Earbuds, 100H Playtime Bluetooth 5.0 IPX8 Waterproof Touch Control True Wireless Bluetooth Earbuds with Mic Earphones in-Ear Deep Bass Built-in Mic Bluetooth Headphones, FlyBuds 3',
 'B0874YS2N7': 'SAMSUNG T7 Portable SSD 500GB - Up to 1050MB/s - USB 3.2 External Solid State Drive, Gray (MU-PC500T/AM)',
 'B08GRFZ2KD': 'Seagate One Touch 5TB External Hard Drive HDD â€“ Black USB 3.0 for PC Laptop and Mac, 1 year MylioCreate, 4 Months Adobe Creative Cloud Photography Plan (STKC5000410)',
 'B08Z3XPWJC': 'Valuetoner Ink Cartridges Replacement for Canon Ink Cartridges 245 and 246 Pg-245Xl Cl-246Xl PG-243 CL-244 Compatible with TR4520 MX492 MX490 MG2420 MG2520 MG2522 MG2920 MG2922 MG3022 MG3029 (1-Pack)',
 'B07HKH2Y56': "ZEMALIA 3 in 1 Male Masturbator Adult Sex Toys with Realistic Textured, Men's Pocket Stroker Toy for Adult Men Masturbation",
 'B07B7K7N3P': 'Furmax Office Chair Mid Back Swivel Lumbar Support Desk Chair, Computer Ergonomic Mesh Chair with Armrest (Black)',
 'B07P83ZSLT': 'ASURION 2 Year Mobile Accident Protection Plan with Tech Support $300-349.99',
 'B08CB25Y6J': 'OTTERBOX COMMUTER SERIES Case for Google Pixel 4a (ONLY, Not compatible with 5G Version) - BLACK',
 'B08CFSZLQ4': 'Google Pixel 4a - Unlocked Android Smartphone - 128 GB of Storage - Up to 24 Hour Battery - Just Black',
 'B08CKNLTLV': 'Poetic Revolution Series for Google Pixel 4a 5.8 inch (2020) Case, Full-Body Rugged Dual-Layer Shockproof Protective Cover with Kickstand and Built-in-Screen Protector, Black',
 'B086H3HH5V': 'Moto E | Unlocked | Made for US by Motorola | 2/32GB | 13MP Camera | 2020 | Blue',
 'B08DN5MC8D': 'Poetic Revolution Series for Moto E 2020 Case, Full-Body Rugged Dual-Layer Shockproof Protective Cover with Kickstand and Built-in-Screen Protector, Black',
 'B00E4LGVUO': 'Panasonic ErgoFit Wired Earbuds, In-Ear Headphones with Microphone and Call Controller, Ergonomic Custom-Fit Earpieces (S/M/L), 3.5mm Jack for Phones and Laptops - RP-TCM125-K (Black)',
 'B098RKWHHZ': 'Nintendo Switch â€“ OLED Model w/ White Joy-Con',
 'B074DQYT25': "NB North Bayou Monitor Arm Desk Mount Ultra Wide Full Motion Swivel Long Arm with Gas Spring for 22''-35''Monitors from 6.6 to 26.4lbs Height Adjustable Monitor Mount Stand F100A-B",
 'B00DQ7WX4U': 'ALOEVINE Original Aloe Drink, 16.9 Fl Oz',
 'B074H64BXB': '365 by Whole Foods Market, Fries Sweet Potato Crinkle Cut, 20 Ounce',
 'B004TLPL82': 'Goya Canilla Extra Long Grain White Rice, 5 Pound',
 'B01M980CKW': 'RIO BRIATI Fresh Mozzarella Ball Sustainably Sourced, 8 oz',
 'B07HKGMPDR': 'Grown in Idaho Super Crispy Crinkle Cut Fries, 28 oz (Frozen)',
 'B00OULBYM8': 'Tyson Fully Cooked Chicken Nuggets, Frozen Chicken Nuggets, 2 lb',
 'B074H7CC1S': '365 by Whole Foods Market, Aloe Vera Juice Drink, 16.9 Fl Oz',
 'B00AR101JM': 'Just BareÃƒÂ‚Ã‚Â® Natural Fresh Chicken Drumsticks | Antibiotic Free | Bone-In | 1.25 LB',
 'B00A445BW4': "Eggland's Best, Large Cage Free Brown Eggs, 1 dozen",
 'B00CIIKU02': 'JUST BARE Natural Fresh Chicken Thighs | Antibiotic Free | Bone-In | 1.25 LB',
 'B00NZL9WSW': 'Tyson Fully Cooked Southern Style Chicken Tenders, 25 oz. (Frozen)',
 'B099JMPP8X': 'Twin Size Bed Frame with Storage Metal 14 Inch Platform Base Foundation Heavy Duty Steel Slats Support Easy Assembly Noise Free No Box Spring Needed Bed Frame Twin Size, Black',
 'B08T1GD3CZ': 'Syncwire USB C to USB C Cable 100W 20V/5A 6.6ft USB Type C PD Fast Charging Cable, Braided Nylon Cord Compatible with MacBook Pro 2020 iPad Pro 2020 Samsung Galaxy S21 S20 S10 Google Pixel',
 'B08F28BH7C': 'USB C Charger, Anker 65W PIQ 3.0 PPS Compact Fast Charger Adapter, PowerPort III Pod Lite, for MacBook Pro/Air, Galaxy S20/S10, Dell XPS 13,Note 10+/10, iPhone 11/Pro, iPad Pro, Pixel, and More',
 'B08XJSWBJP': 'Lewis N. Portable Immersion Water Heater + Electric Kettle Alternative for Coffee, Tea + Hot Chocolate, Camping, Travel + Office w/Travel Adapter, Black, 120/240v',
 'B09PDM2VDP': 'Pussy Ass Male Masturbators for Cowgirl Style Sex, Plump Butt Masturbator with 3D Tight Vagina Anal Channel ,Goyha Adult Sex Toys with Sexy Curves and Soft Skin for Men Masturbation (5.8LB)',
 'B08TGR7GYT': 'PoeticÂ\xa0RevolutionÂ\xa0SeriesÂ\xa0CaseÂ\xa0forÂ\xa0MotorolaÂ\xa0MotoÂ\xa0OneÂ\xa05GÂ\xa0AceÂ\xa0(2021),Â\xa0Full-BodyÂ\xa0RuggedÂ\xa0Dual-LayerÂ\xa0ShockproofÂ\xa0ProtectiveÂ\xa0CoverÂ\xa0withÂ\xa0KickstandÂ\xa0andÂ\xa0Built-in-ScreenÂ\xa0Protector,Â\xa0Black',
 'B005F9XFN0': 'NOW Foods, Certified Organic Better Stevia, Extract Powder, Zero-Calorie Sweetener, Certified Non-GMO, 4-Ounce',
 'B000HHSHZG': "F.M. Brown'S Encore Parakeet Food, 5-Pound",
 'B014V1IYEM': 'COTTON CRAFT - Scandia Stripe 12 Pack - Pure Cotton - Professional Commercial Restaurant Grade Kitchen Dish Tea Towel Cloth Napkins - Low Lint Sturdy Weave - Reusable - 16x28-30 Ounces - Charcoal',
 'B01K4JKFK6': 'XREXS 4 Channels Digital Kitchen Timer Clock, Cooking Timer with Large LCD Display, 4 Groups Simultaneous Timing Countdown Up Pocket Timer, Magnetic Attachable (Battery Included) (396)',
 'B01A92ETXM': 'Premium Wrist Rests for Keyboard and Mouse Pad Set - Memory Foam Cushion, Black - Ergonomic Wrists Hand Arm Rest Support for Laptop Computer Desk and Gaming - Carpal Tunnel Syndrome Relief',
 'B009LENJHW': 'Natrol Melatonin Fast Dissolve Tablets, Helps You Fall Asleep Faster, Stay Asleep Longer, Easy to Take, Dissolves in Mouth, Strengthen Immune System, 3mg, 90 Count',
 'B0078DP17Y': 'Celtic Sea Salt, Light Grey Grinder, 3 oz White',
 'B00TH7HTD8': "Burt's Bees Facial Cleansing Towelette Wipes for Sensitive Skin with Cotton Extract, 30 Count (Package May Vary)",
 'B01IR2I79S': 'U by Kotex Lightdays Liners, Regular, Unscented',
 'B074G9XFPY': 'Amazon Brand - Presto! Biobased Hand Soap, Mandarin Currant Scent',
 'B074GBVT9T': 'Amazon Brand - Presto! Biobased Hand Soap, Lime Mint Scent, 12 fl oz',
 'B074G9FH13': 'Amazon Brand - Presto! Biobased Hand Soap, Citrus Hibiscus Scent',
 'B013SRDRBA': 'Aussie Total Miracle Collection Shampoo, 26.2 Fl Oz (Pack of 1)',
 'B0713WYWVF': 'Neutrogena Healthy Skin Boosters Facial Cleanser with Moisturizing Vitamin E and Antioxidant White Tea for Healthy Looking Skin, Oil-Free, 9 fl. oz',
 'B01EMZ7QK0': "Johnson's Baby Bedtime Bubble Bath and Wash, 15 Ounce",
 'B0182G6OAI': 'Neutrogena Naturals Multi-Vitamin Moisturizing & Nourishing Night Face Cream with Antioxidant Bionutrients & Vitamins B, C & E, Non-Comedogenic & Sulfate-, Paraben-, Phthalate- & Dye-Free, 1.7 oz',
 'B001B13THI': 'Food Should Taste Good Tortilla Chips, Multigrain, Gluten Free, 5.5 oz',
 'B00J0AYYBW': 'Clorox Handi Wipes Heavy Duty Reusable Cloths, 3 Count',
 'B00NAZ5RIC': 'Kleenex Trusted Care Everyday Facial Tissues, Flat Box,',
 'B01BGN1GN4': 'Jyoti Natural Foods Chhole, Chickpeas with Potatoes and Onions, 15 Ounce',
 'B00ULKSVQY': 'Suave Essentials Body Wash, Mango Mandarin, 15 oz',
 'B00NPNS9RU': 'Damage Repair - Aussie Paraben-Free Total Miracle 3 Minute Miracle Conditioner w/Apricot, 8.0 fl oz (Packaging May Vary)',
 'B01MTCOI2A': 'NUTRO NATURAL CHOICE Small Breed Senior Dry Dog Food, Chicken & Brown Rice Recipe Dog Kibble, 5 lb. Bag',
 '1625233000': 'TASC Strategies, Practice & Review 2017-2018 with 2 Practice Tests: Online + Book (Kaplan Test Prep)',
 '1506223605': 'GED Test Prep Plus 2018: 2 Practice Tests + Proven Strategies + Online (Kaplan Test Prep)',
 'B0716LBRPS': "Amazon Brand - Daily Ritual Women's Skinny Stretch Jegging",
 'B016C18EH6': 'LDR INDUSTRIES 163 3000SN 3PC BATH ORGANIZER KIT SATIN NICKEL, NICKLE',
 'B073Z83BR4': 'EVISTR Micro USB Cable Android Charger - 3 Pack 6FT Micro USB Charging Cable High Speed Sync Data Nylon Braided Cord Compatible with Samsung S7 S6 J7 Note 5 Kindle M3 Player, Micro USB Charger Devices',
 'B00Y1YD8PK': 'Headphone Splitter, 5-Jack 3.5 mm Audio Headphone Splitter Stereo Audio Headset Adapter, Audio Earbuds Earphones Plug 5 Way 1 Male to 4 Female Splitter with 3.5mm Stereo Cable',
 'B01M4S7ZGM': 'Monitor Stand Riser, 2 Tiers Wood Monitor Riser Stand with Storage Organizer, Desktop Ergonomic Monitor Stand Riser with Cellphone Holder and Cable Management, 16.5 Inch Shelf Black',
 'B06X9NJBM4': 'Kiss My Face Patchouli Bath and Body Wash 32 OZ',
 'B007EGFQBQ': 'Aussie Moist Conditioner With Pump 29.2 Fluid Ounce',
 'B00SSTF8LQ': 'Large Cosmetic Bag With Big Clear Mirror Full Of Capacity For Organize All Of Your Makeups (Coffee)',
 'B0142INY7G': 'carefresh Dust-Free Confetti Natural Paper Small Pet Bedding with Odor Control, 10L',
 'B0749HQ8QV': '[J.ESTINA BEAUTY] Jewel Tension Tinted Lip Balm (Black Cherry) - Nourishing, Hydrating and Moisturizing with Vivid Colors',
 'B0052Z82K8': 'Rimmel Professional Eyebrow Dark Brown',
 'B06XX29S9Q': 'SAMSUNG (MB-ME64GA/AM) 64GB 100MB/s (U3) MicroSDXC EVO Select Memory Card with Full-Size Adapter',
 'B0186QMA4S': 'TSA Approved Travel Combination Cable Luggage Locks for Suitcases & Backpacks - 1 Pack of Orange TSA Lock',
 'B07BBFY3CH': 'Small Led Grow Light, CFGROW Desk Clip LED Plant Grow Lamp 7W with 360Â° Flexible Gooseneck for Indoor Office Home Garden Greenhouse Plants Growing Lighting (7W)',
 'B00856I3E6': 'Sheer Guard Bird Cage Skirt-Made in USA - Medium Size (Aqua)',
 '1573226327': 'Awakening at Midlife: A Guide to Reviving Your Spirit, Recreating Your Life, and Returning to Your Truest Self',
 '0062465600': 'Mermaids in Wonderland: A Coloring and Puzzle-Solving Adventure for All Ages',
 'B000TZ1X4S': 'Simple Solution Hard Floor Pet Stain and Odor Remover | Dual Action Cleaner for Sealed Hardwood Floors | 32 Ounces',
 'B00000JQ4I': 'TY Beanie Baby - GOATEE the Goat',
 '1977537189': '2018 Tarot Planner',
 'B00GL64QG6': 'ZEISS Pre-Moistened Lens Cleaning Wipes, 200 Count',
 'B01N48TSVK': 'Whispers Feminine Care Set, Intimate Care, pH Balanced by R. Drew Naturals',
 'B00MHTGICQ': 'Snappy Popcorn, White, 4 Pound',
 'B01NC2Y1AB': 'Hidden Valley Buttermilk Ranch Salad Dressing & Topping, Gluten Free, Keto-Friendly - 36 Ounce Bottle (Package May Vary)',
 'B074MGQ1R4': '365 Everyday Value, Chili Powder Blend, 7.62 oz',
 'B000QSHOPA': 'Oregon Chai Original Chai Tea Latte Concentrate, 32 Fl Oz (Pack of 1)',
 'B00OKEUVXI': 'Tasty Bite Indian Bombay Potatoes 10 Ounce, Fully Cooked Indian EntrÃ©e with Chickpeas and Potatoes with Spices in a Tomato Sauce, Vegan, Gluten Free, Microwaveable, Ready to Eat',
 'B075N1QTTG': '365 Everyday Value, Indian Basmati White Rice, 32 Ounce',
 'B074MFQVSV': '365 Everyday Value, Wasabi Rice Crackers, 3.57 Ounce',
 'B074M992MC': 'Whole Paws, Small Dog Biscuits, Assorted Flavors, 10 Ounce',
 'B074MHFN47': '365 Everyday Value, Veggie Straws, 6 Ounce',
 'B074MHN2KJ': 'Whole Foods Market, Lavender Vanilla Fizzing Bath Bomb, 2.3 Ounce',
 'B074MG12QS': '365 Everyday Value, Shells & Alfredo, 7.25 oz',
 'B074MGZFQC': '365 Everyday Value, Chocolate Sandwich Cremes, 20 Ounce',
 'B01GCT2F00': 'Pepsi Cola Soda Pop, 16.9oz Bottles (6 Pack)',
 'B074MH3FM1': '365 Everyday Value, Organic Medium Salsa - Thick & Chunky, 38 Ounce',
 'B00UB6T2I4': 'Colgate Extra Clean Full Head Toothbrush, Medium - 4 Count',
 'B013SRDJ40': 'Head and Shoulders Instant Oil Control Daily-Use Anti-Dandruff Shampoo, 12.8 fl oz',
 'B00UB6E4IM': 'TRESemmÃ© Rich Moisture Conditioner for Dry Hair Formulated With Pro Style Technology 28 oz',
 'B00I9JK8GU': "Ziploc Freezer Bags with New Grip 'n Seal Technology, Gallon, 28 Count",
 'B01MQQB5VN': 'SparkleÂ® Pick-A-Size Paper Towels, 2 Rolls = 3 Regular Rolls, 116 2-Ply Sheets Per Roll',
 'B074MHFNH5': '365 Everyday Value, Macaroni & Cheese, 7.25 Ounce',
 'B06XB3ZS4T': 'Kodiak Cakes Power Bake, Non GMO, Protein Packed Muffin Mix, Double Dark Chocolate, 14 Ounce - No Preservatives',
 'B074MG5VVJ': '365 Everyday Value, Saltine Crackers, 16 Ounce',
 'B00008CMPY': 'GUM - 760RB Dual Action Tongue Cleaner Brush and Scraper (Colors May Vary)',
 'B015OT4QD8': 'CTS Air Plants Tillandsia Ionantha Assorted 3 Pack',

In [19]:
# Merging the new codes dataframe with our data to fill in product titles
data['Title'] = data['ASIN/ISBN (Product Code)'].map(codes_dict)


data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 30 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   Order Date                  1048575 non-null  str
 1   Purchase Price Per Unit     1048575 non-null  float64
 2   Quantity                    1048575 non-null  float64
 3   Shipping Address State      997480 non-null   str
 4   Title                       998235 non-null   str
 5   ASIN/ISBN (Product Code)    1047967 non-null  str
 6   Category                    997766 non-null   str
 7   Survey ResponseID           1048575 non-null  str
 8   Q-demos-age                 1048575 non-null  str
 9   Q-demos-hispanic            1048575 non-null  str
 10  Q-demos-race                1048575 non-null  str
 11  Q-demos-education           1048575 non-null  str
 12  Q-demos-income              1048575 non-null  str
 13  Q-demos-gender              1048575 non-null  str
 14  Q-sexual-orientation        1048575 non-null  str
 15  Q-demos-state               1048575 non-null  str
 16  Q-amazon-use-howmany        1048575 non-null  str
 17  Q-amazon-use-hh-size        1048575 non-null  str
 18  Q-amazon-use-how-oft        1048575 non-null  str
 19  Q-substance-use-cigarettes  1048575 non-null  str
 20  Q-substance-use-marijuana   1048575 non-null  str
 21  Q-substance-use-alcohol     1048575 non-null  str
 22  Q-personal-diabetes         1048575 non-null  str
 23  Q-personal-wheelchair       1048575 non-null  str
 24  Q-life-changes              337784 non-null   str
 25  Q-sell-YOUR-data            1048575 non-null  str
 26  Q-sell-consumer-data        1048575 non-null  str
 27  Q-small-biz-use             1048575 non-null  str
 28  Q-census-use                1048575 non-null  str
 29  Q-research-society          1048575 non-null  str
dtypes: float64(2), str(28)
memory usage: 240.0 MB

In [21]:
# Repeating this process to fill in categories

cats = data[['ASIN/ISBN (Product Code)', 'Category']].drop_duplicates().dropna()
cats_dict = cats.set_index('ASIN/ISBN (Product Code)')['Category'].to_dict()
cats_dict

{'B0143RTB1E': 'FLASH_MEMORY',
 'B01MA1MJ6H': 'HEADPHONES',
 'B06XWF9HML': 'DISHWARE_BOWL',
 'B00837ZOI0': 'SHAVING_AGENT',
 'B01GFB2E9M': 'ELECTRONIC_CABLE',
 'B00NH13S44': 'ELECTRONIC_CABLE',
 'B077H6L7T9': 'AMAZON_TABLET',
 'B07L84ZZXC': 'APPAREL_BELT',
 'B07CG71KQ1': 'PORTABLE_ELECTRONIC_DEVICE_STAND',
 'B079GFF4HZ': 'HEADPHONES',
 'B01M0Q84BR': 'IMMERSION_HEATER',
 'B073JYC4XM': 'FLASH_MEMORY',
 'B00I7DT454': 'BODY_LUBRICANT',
 'B0043T7FXE': 'INPUT_MOUSE',
 'B01M2V05RE': 'HEADPHONES',
 'B07BCZMBNR': 'CELLULAR_PHONE_CASE',
 'B075CMYT43': 'BODY_POSITIONER',
 'B01MZ956SX': 'HANDBAG',
 'B07JCJP1DK': 'UNDERPANTS',
 'B07JD5B8SP': 'UNDERPANTS',
 'B071XGLB1S': 'TAPE_MEASURE',
 'B071ZBV7DY': 'AMAZON_TABLET_ACCESSORY',
 'B07D5V2ZXD': 'COMPUTER_DRIVE_OR_STORAGE',
 'B01BNEWDFQ': 'TOOTH_CLEANING_AGENT',
 'B01NBYY28W': 'TOILET_PAPER',
 'B019FGCOW6': 'MOUTHWASH',
 'B072JYDQ7N': 'ELECTRONIC_CABLE',
 'B00MUJU33S': 'SCREWDRIVER',
 'B07RTN4C77': 'ELECTRONIC_GIFT_CARD',
 'B01IQ00B04': 'EDIBLE_OIL_VEGETABLE',
 'B017ALC6GW': 'EDIBLE_OIL_VEGETABLE',
 'B0741FV7ZV': 'SIM_CARD',
 'B006MIPW70': 'BED_FRAME',
 'B01LZKYNIM': 'HERB',
 'B00NC8QEKM': 'MEAT',
 'B0011EKWBQ': 'GROCERY',
 'B00NC882CA': 'DAIRY_BASED_CHEESE',
 'B00B9GUZP4': 'JERKY',
 'B000QD9C8M': 'BODY_LUBRICANT',
 'B01LZ5SB6U': 'SEXUAL_STIMULATION_DEVICE',
 'B072HRDM55': 'FLASH_MEMORY',
 'B07DGQ4QR3': 'BODY_LUBRICANT',
 'B06XWZWYVP': 'FLASH_MEMORY',
 'B07H8GC6WL': 'SEXUAL_STIMULATION_DEVICE',
 'B01DVLP2UW': 'SEXUAL_STIMULATION_DEVICE',
 'B075SN1MY9': 'BODY_LUBRICANT',
 'B07GKKSXBS': 'FILE_FOLDER',
 'B001U0PA7M': 'IMMERSION_HEATER',
 'B00GAC1D2G': 'GIFT_CARD',
 'B083V5CFMP': 'HEADPHONES',
 'B07F42TGQF': 'ELECTRONIC_CABLE',
 'B072PW59TZ': 'PORTABLE_ELECTRONIC_DEVICE_COVER',
 'B07VDDDPKY': 'MEMORY_CARD_READER',
 'B0866C659Q': 'HEADPHONES',
 'B00IX1I3G6': 'GIFT_CARD',
 'B07R6RR3RQ': 'STORAGE_BAG',
 'B015PPQXY6': 'ELECTRONIC_CABLE',
 'B08GQF2SGQ': 'COMPUTER_DRIVE_OR_STORAGE',
 'B07TJVXNHX': 'HEADPHONES',
 'B088LW4JKR': 'HEADPHONES',
 'B0874YS2N7': 'COMPUTER_DRIVE_OR_STORAGE',
 'B08GRFZ2KD': 'COMPUTER_DRIVE_OR_STORAGE',
 'B08Z3XPWJC': 'INKJET_PRINTER_INK',
 'B07HKH2Y56': 'SEXUAL_STIMULATION_DEVICE',
 'B07B7K7N3P': 'CHAIR',
 'B07P83ZSLT': 'CONSUMER_ELECTRONICS',
 'B08CB25Y6J': 'CELLULAR_PHONE_CASE',
 'B08CFSZLQ4': 'CELLULAR_PHONE',
 'B08CKNLTLV': 'CELLULAR_PHONE_CASE',
 'B086H3HH5V': 'CELLULAR_PHONE',
 'B08DN5MC8D': 'CELLULAR_PHONE_CASE',
 'B00E4LGVUO': 'HEADPHONES',
 'B098RKWHHZ': 'VIDEO_GAME_CONSOLE',
 'B074DQYT25': 'FLAT_SCREEN_DISPLAY_MOUNT',
 'B00DQ7WX4U': 'GROCERY',
 'B074H64BXB': 'SNACK_CHIP_AND_CRISP',
 'B004TLPL82': 'GROCERY',
 'B01M980CKW': 'DAIRY_BASED_CHEESE',
 'B07HKGMPDR': 'FOOD',
 'B00OULBYM8': 'POULTRY',
 'B074H7CC1S': 'JUICE_AND_JUICE_DRINK',
 'B00AR101JM': 'POULTRY',
 'B00A445BW4': 'POULTRY',
 'B00CIIKU02': 'POULTRY',
 'B00NZL9WSW': 'POULTRY',
 'B099JMPP8X': 'BED_FRAME',
 'B08T1GD3CZ': 'ELECTRONIC_CABLE',
 'B08F28BH7C': 'CHARGING_ADAPTER',
 'B08XJSWBJP': 'IMMERSION_HEATER',
 'B09PDM2VDP': 'SEXUAL_STIMULATION_DEVICE',
 'B08TGR7GYT': 'CELLULAR_PHONE_CASE',
 'B005F9XFN0': 'SUGAR_SUBSTITUTE',
 'B000HHSHZG': 'PET_FOOD',
 'B014V1IYEM': 'TOWEL',
 'B01K4JKFK6': 'TIMER',
 'B01A92ETXM': 'WRIST_REST',
 'B009LENJHW': 'HEALTH_PERSONAL_CARE',
 'B0078DP17Y': 'CULINARY_SALT',
 'B00TH7HTD8': 'SKIN_CLEANING_WIPE',
 'B01IR2I79S': 'SANITARY_NAPKIN',
 'B074G9XFPY': 'SKIN_CLEANING_AGENT',
 'B074GBVT9T': 'SKIN_CLEANING_AGENT',
 'B074G9FH13': 'SKIN_CLEANING_AGENT',
 'B013SRDRBA': 'SHAMPOO',
 'B0713WYWVF': 'BEAUTY',
 'B01EMZ7QK0': 'BATHWATER_ADDITIVE',
 'B0182G6OAI': 'BEAUTY',
 'B001B13THI': 'SNACK_CHIP_AND_CRISP',
 'B00J0AYYBW': 'SURFACE_CLEANING_WIPE',
 'B00NAZ5RIC': 'FACIAL_TISSUE',
 'B01BGN1GN4': 'SAUCE',
 'B00ULKSVQY': 'SKIN_CLEANING_AGENT',
 'B00NPNS9RU': 'CONDITIONER',
 'B01MTCOI2A': 'PET_FOOD',
 '1625233000': 'ABIS_BOOK',
 '1506223605': 'ABIS_BOOK',
 'B0716LBRPS': 'PANTS',
 'B016C18EH6': 'PLUMBING_FIXTURE',
 'B073Z83BR4': 'ELECTRONIC_CABLE',
 'B00Y1YD8PK': 'ELECTRONIC_ADAPTER',
 'B01M4S7ZGM': 'ITEM_STAND',
 'B06X9NJBM4': 'BEAUTY',
 'B007EGFQBQ': 'CONDITIONER',
 'B00SSTF8LQ': 'COSMETIC_CASE',
 'B0142INY7G': 'PET_BED_MAT',
 'B0749HQ8QV': 'LIP_BALM',
 'B0052Z82K8': 'EYEBROW_COLOR',
 'B06XX29S9Q': 'FLASH_MEMORY',
 'B0186QMA4S': 'LOCK',
 'B07BBFY3CH': 'LAMP',
 'B00856I3E6': 'FURNITURE_COVER',
 '1573226327': 'ABIS_BOOK',
 '0062465600': 'ABIS_BOOK',
 'B000TZ1X4S': 'CLEANING_AGENT',
 'B00000JQ4I': 'TOY_FIGURE',
 '1977537189': 'ABIS_BOOK',
 'B00GL64QG6': 'HEALTH_PERSONAL_CARE',
 'B01N48TSVK': 'GUILD_BEAUTY_GROOMING',
 'B00MHTGICQ': 'POPCORN',
 'B01NC2Y1AB': 'SALAD_DRESSING',
 'B074MGQ1R4': 'HERB',
 'B000QSHOPA': 'TEA',
 'B00OKEUVXI': 'GROCERY',
 'B075N1QTTG': 'CEREAL',
 'B074MFQVSV': 'CRACKER',
 'B074M992MC': 'PET_FOOD',
 'B074MHFN47': 'GROCERY',
 'B074MHN2KJ': 'GROCERY',
 'B074MG12QS': 'GROCERY',
 'B074MGZFQC': 'COOKIE',
 'B01GCT2F00': 'DRINK_FLAVORED',
 'B074MH3FM1': 'SAUCE',
 'B00UB6T2I4': 'TOOTHBRUSH',
 'B013SRDJ40': 'SHAMPOO',
 'B00UB6E4IM': 'CONDITIONER',
 'B00I9JK8GU': 'FOOD_STORAGE_BAG',
 'B01MQQB5VN': 'PAPER_TOWEL',
 'B074MHFNH5': 'DAIRY_BASED_CHEESE',
 'B06XB3ZS4T': 'BAKING_MIX',
 'B074MG5VVJ': 'CRACKER',
 'B00008CMPY': 'PROFESSIONAL_HEALTHCARE',
 'B015OT4QD8': 'PLANT_SEED',
 'B01KNHWAT8': 'SWEATSHIRT',
 'B00FBT7XAK': 'PET_FOOD',
 'B01N4TQSJP': 'PET_FOOD',
 'B01HFIRVJM': 'PEST_CONTROL_DEVICE',
 'B002IGTP00': 'MUSICAL_INSTRUMENT_TOY',
 'B0019BK8AG': 'INSECT_REPELLENT',
 'B071WGR9GG': 'CHARGING_ADAPTER',
 'B005P0U7TY': 'HERBAL_SUPPLEMENT',
 'B00005W9ZZ': 'ABIS_BOOK',
 'B07882QJX9': 'HAT',
 'B077SZS7NR': 'PANTS',
 'B07HKGBLZ3': 'COAT',
 'B01N5XH704': 'NOTEBOOK_COMPUTER',
 'B0749CCDM6': 'HAIR_BRUSH',
 'B075N83693': 'NAIL_CLIPPER',
 'B01HIK9DU2': 'PANTS',
 'B07DK7QHN8': 'SWEATER',
 'B01BT02Q88': 'SKIN_SERUM',
 'B0084Y1M8I': 'NUTRITIONAL_SUPPLEMENT',
 'B001TMIR1C': 'ABIS_BOOK',
 '0786965592': 'TOYS_AND_GAMES',
 'B07HMC4S1D': 'BLANK_BOOK',
 'B00DF2UK4G': 'PET_FOOD',
 'B01M5DS0Z7': 'PET_SUPPLIES',
 'B0067H6KP4': 'SKIN_MOISTURIZER',
 '1449489745': 'CALENDAR',
 'B002GHC66Q': 'PANTS',
 'B075B295PS': 'PLANNER',
 'B079GZJF4K': 'OFFICE_PRODUCTS',
 'B074CTMZ3Y': 'TOILET_PAPER',
 'B010BVZ1VU': 'BODY_DEODORANT',
 'B01JFILPIS': 'WINDOW_FILM',
 'B00K692TN6': 'NAIL_POLISH',
 'B075JJH4KQ': 'MEDICATION',
 '1441324097': 'ABIS_BOOK',
 'B000BODSZY': 'HARDWARE_HANDLE',
 'B079FLCYBH': 'ELECTRONIC_CABLE',
 'B01DBGVB7K': 'NOTEBOOK_COMPUTER',
 'B00OI20SXA': 'PET_SUPPLIES',
 'B07JRBKQVX': 'GARMENT_STEAMER',
 'B07DD7L7S7': 'FLASHLIGHT',
 'B07D439MFV': 'MOP_BUCKET_SET',
 'B07L4DW1VT': 'TEMPORARY_GATE',
 'B07CVQXC66': 'BED_FRAME',
 '073874784X': 'ABIS_BOOK',
 'B07L1936ZQ': 'BODY_POSITIONER',
 'B01EIKB5CO': 'INCENSE',
 'B07484MGHL': 'SKIRT',
 'B01JZ4KOFC': 'SHIRT',
 'B007V7ZHQW': 'SKIN_MOISTURIZER',
 'B06XV9RNR2': 'DRESS',
 'B015WZKGN8': 'BONDING_ADHESIVES',
 'B07CZBP3X5': 'WALL_ART',
 'B00P8QIC0Q': 'HANGING_ROD',
 'B008HBMQTM': 'SKIN_CLEANING_WIPE',
 'B07H7SSR9D': 'TOOTHBRUSH',
 'B00NM2G0E8': 'PET_FOOD',
 'B01G8HUH8S': 'FORK',
 'B07M98TRYD': 'FOOD_SPATULA',
 'B0002DH2YW': 'PET_FOOD',
 'B07GJ13K9T': 'ABIS_HOME',
 'B0794XF6XK': 'CELLULAR_PHONE_CASE',
 'B07GP13TH1': 'UMBRELLA',
 'B072YS3PVM': 'SURFACE_CLEANING_WIPE',
 'B07GRCD85S': 'EARPLUG',
 'B014EDYKO0': 'SKIN_CLEANING_WIPE',
 'B07MSF4WHY': 'TOOTHBRUSH_HOLDER',
 'B06XKTNRNS': 'PET_PEST_CONTROL',
 'B00DM1DDBW': 'HAIR_BRUSH',
 'B01GM1LUGS': 'PEST_CONTROL_DEVICE',
 'B01N5X7AK7': 'HAIR_CLIP',
 'B07V9Q58LJ': 'ELECTRONIC_CABLE',
 'B07PPRGPF1': 'PEST_CONTROL_DEVICE',
 'B0743ML7K6': 'NUTS',
 'B01D9OS5KA': 'HOME',
 'B07MCV47L1': 'NAIL_FILE',
 'B004RKPV2Q': 'EYELID_COLOR',
 '1083121448': 'ABIS_BOOK',
 'B004MYPWEO': 'CANDLE',
 'B000UGM32C': 'BONDING_ADHESIVES',
 'B0050FI1P6': 'YARN',
 'B000QHDAZE': 'KNITTING_NEEDLE',
 'B07PRN81SP': 'SHIRT',
 'B07VQSY6M3': 'SHIRT',
 'B07JP583BD': 'PANTS',
 'B07WFDRFDJ': 'TUNIC',
 'B07Q7PCFJ4': 'SHIRT',
 'B06W5PD1KY': 'MICROCURRENT_FACIAL_MACHINE',
 'B07MLSSZZF': 'FOOD_STORAGE_CONTAINER',
 'B01N9SIMUE': 'HAND_SEWING_NEEDLE',
 'B0002ASIA2': 'PET_SUPPLIES',
 'B075WRCVL2': 'APPAREL_GLOVES',
 'B07SYL1H6B': 'UMBRELLA',
 'B00JE301ZI': 'SOCKS',
 'B07JZKYVD8': 'PET_FOOD',
 'B000XAOKPS': 'BONDING_ADHESIVES',
 'B07JQ3G816': 'ENVELOPE',
 'B01MTYL3HS': 'POWER_CORD',
 'B00SNKR4PS': 'STRING_LIGHT',
 'B07XVFYW5T': 'NUTRITIONAL_SUPPLEMENT',
 'B01LB8G508': 'SHIRT',
 'B0039UMRMW': 'ART_MEDIA_PAPER',
 'B00E3EXC7M': 'ART_AND_CRAFT_SUPPLY',
 'B07PY38D97': 'HEADPHONES',
 'B016ECMESI': 'HAT',
 'B07JZJZ82N': 'PET_FOOD',
 'B01MY5EE0A': 'SKIN_CLEANING_WIPE',
 'B07SXD5ZGF': 'ORTHOPEDIC_BRACE',
 '144949692X': 'ABIS_BOOK',
 'B07S287H9F': 'CALENDAR',
 'B07DDLHC4G': 'AIR_PURIFIER',
 'B075LNRS3C': 'SOCKS',
 'B00MJ7VL1O': 'HERBAL_SUPPLEMENT',
 'B000XFA5FW': 'SHOES',
 'B07XTQ5N69': 'PITCHER',
 'B07Y9D4TCJ': 'PLANTER',
 'B07VY8HRHZ': 'SOIL',
 'B07WS6SK2X': 'LIGHT_BULB',
 'B004FP9P0M': 'INCENSE',
 'B074H5Z5T4': 'SAUCE',
 'B01HOFJT28': 'DAIRY_BASED_ICE_CREAM',
 'B07NRCVJR2': 'DISHWARE_PLATE',
 'B01MDUFUV2': 'DAIRY_BASED_ICE_CREAM',
 'B0146YCU8A': 'FRUIT',
 'B01M35BS3M': 'DAIRY_BASED_ICE_CREAM',
 'B074H58YCT': 'VEGETABLE',
 'B071DWP99K': 'FOOD_STORAGE_BAG',
 'B01FEG59YG': 'CONDITIONER',
 'B0773P4PM9': 'DAIRY_BASED_ICE_CREAM',
 'B081289WL5': 'FRUIT',
 'B074HBMG5Y': 'SHAMPOO',
 'B07H4VJCRB': 'FOOD_STORAGE_CONTAINER',
 'B013KB26CK': 'FOOD_STORAGE_CONTAINER',
 'B01H2DG11O': 'SHOWERHEAD',
 'B00PJ9K2BE': 'HARDWARE_HANDLE',
 'B00068TGWE': 'PLANT_SEED',
 'B07BFRC6G5': 'HERBAL_SUPPLEMENT',
 'B00028MCZQ': 'HERBAL_SUPPLEMENT',
 'B07BDH1MGP': 'LAUNDRY_HAMPER',
 'B07FP3QL8R': 'LAUNDRY_HAMPER',
 'B01AY52LFM': 'PET_FOOD',
 'B007YAB5J4': 'HEALTH_PERSONAL_CARE',
 'B00C5H5DN0': 'FLAT_SCREEN_DISPLAY_MOUNT',
 'B00B2F8BOY': 'TRASH_CAN',
 'B00PRYQ9YU': 'PINBOARD',
 'B07VPW7HJM': 'DESK',
 'B07T8L539L': 'CHAIR',
 'B005AX7OLU': 'HVAC_AIR_FILTER',
 'B014EKQ5AA': 'POWER_STRIP',
 'B07JH8GQRG': 'TOWEL',
 'B00BJCV6JC': 'UTILITY_SPONGE',
 'B0007PQAX4': 'VITAMIN',
 'B07X59YXFH': 'HERBAL_SUPPLEMENT',
 'B004R5ZJQ4': 'VITAMIN',
 'B00O869QUC': 'BATTERY',
 'B07W3K9WYW': 'CLOTHES_PIN',
 'B07SJMZVC8': 'APRON',
 'B002Z6ZS0E': 'OFFICE_PRODUCTS',
 'B07KG66XZX': 'SHARP_PIN',
 'B00ED3PJ2Y': 'JANITORIAL_SUPPLY',
 'B00IJUNQXG': 'LAMP',
 'B00763LZWQ': 'TOOTHBRUSH',
 'B00006IF1T': 'FILE_FOLDER',
 'B07254ZQYQ': 'STORAGE_RACK',
 'B002LF0J1M': 'PET_FOOD',
 'B0002563MM': 'HARDWARE_TUBING',
 'B07PD6BYQT': 'HARDWARE_HINGE',
 'B07KW23P34': 'SEWING_TOOL_SET',
 'B004W6W8OO': 'NUTRITIONAL_SUPPLEMENT',
 'B00178KMIE': 'BONDING_ADHESIVES',
 'B00KD6ZHD6': 'BONDING_ADHESIVES',
 'B07PCMWTSG': 'GIFT_CARD',
 'B0081G86QU': 'NUTRITIONAL_SUPPLEMENT',
 'B00LZ7TNRI': 'FLOUR',
 'B005G8T32M': 'HERB',
 'B0002IU8K2': 'FERTILIZER',
 'B01FDD79AW': 'LAMP',
 'B07JJNMKFM': 'BLUE_LIGHT_BLOCKING_EYEGLASSES',
 'B06XB79BP1': 'ROLLING_PIN',
 '0385543786': 'ABIS_BOOK',
 'B00X6HB7K6': 'BROOM',
 'B07NJNKW75': 'PLANTER',
 'B074H6G7C3': 'DAIRY_BASED_CHEESE',
 'B078W62HGN': 'COOKIE',
 'B0787Y5D9C': 'FRUIT',
 'B00UGBUZ1M': 'BREAD',
 'B0787YC1HY': 'FRUIT',
 'B079VQSVYP': 'FRUIT',
 'B000O6EFGK': 'EDIBLE_OIL_VEGETABLE',
 'B074H4SHLR': 'DAIRY_BASED_DRINK',
 'B07MJ3QSVS': 'RAW_MATERIALS',
 'B003W8JSH8': 'COFFEE_MAKER',
 'B077FH58XN': 'FLAVORED_DRINK_CONCENTRATE',
 'B00ITXIL7E': 'FLAVORED_DRINK_CONCENTRATE',
 'B004S0PGPM': 'SHOVEL_SPADE',
 'B0756DXV8M': 'CLOTHES_HANGER',
 'B004JFXAZY': 'GARLAND',
 'B0021ACTIS': 'MEDICATION',
 'B01G0O6GPW': 'TOWEL',
 'B0746KXXYR': 'PLANTER',
 'B075PF145D': 'HAIR_CLIP',
 'B01K8DB372': 'MEDICATION',
 'B017JDD048': 'SHOES',
 'B083N2W7K9': 'DISPLAY_ALBUM',
 'B07WYVWDPF': 'PET_SUPPLIES',
 'B07YZPZRJT': 'ICE_CUBE_TRAY',
 'B016M89MLQ': 'SKIN_CLEANING_AGENT',
 'B07BHYGRV8': 'MEDICATION',
 'B00004Z47L': 'ADHESIVE_TAPES',
 'B009K6TN08': 'MINERAL_SUPPLEMENT',
 'B07HGZCVZ3': 'ELECTRONIC_CABLE',
 'B007CRDSV2': 'PET_FOOD',
 'B00VBUYGNA': 'MANUAL_SHAVING_RAZOR',
 'B00X1MUJ28': 'BODY_DEODORANT',
 '8915094549': 'ABIS_BOOK',
 'B079XFV2DW': 'PANTS',
 'B00MW8NBW2': 'KITCHEN',
 'B00M3ZKKXC': 'UNDERPANTS',
 'B01LDNBC86': 'SUGAR_SUBSTITUTE',
 'B07WRMFQG5': 'DRAIN_STRAINER',
 'B00006J3G2': 'MEDICATION',
 'B0009KN8UA': 'SHAMPOO',
 'B081VFG24B': 'COSMETIC_BRUSH',
 'B082KFJDQS': 'SKIN_EXFOLIANT',
 'B07JYLWSGH': 'SKIN_TREATMENT_MASK',
 'B083S4WVQY': 'SKIN_TREATMENT_MASK',
 'B01B4D01HI': 'SKIN_EXFOLIANT',
 'B07MB4HN9X': 'GIFT_CARD',
 'B07QWTZCWC': 'HAT',
 'B07BXF33WN': 'SUNGLASSES',
 'B08CMQ79BV': 'LIGHT_BULB',
 'B07F8JWRFJ': 'PACKAGED_SOUP_AND_STEW',
 'B01LWS9514': 'DISPOSABLE_INCONTINENCE_SURFACE_PROTECTOR',
 'B07R4XLTR5': 'UNDERPANTS',
 'B07MJ87WS5': 'MEDICATION',
 'B07HNR78WM': 'ART_SUPPLIES',
 '1934170291': 'ABIS_BOOK',
 'B07VW5VXN9': 'SOCKS',
 'B07D37DDG7': 'DRESS',
 '1607745771': 'ABIS_BOOK',
 'B07SRK6MWN': 'BLANK_BOOK',
 'B07Z5FLHL8': 'SKIN_CLEANING_WIPE',
 'B07MHKXS52': 'FOOD_STORAGE_CONTAINER',
 'B073HNVM2K': 'CADDY',
 'B005AXNHD4': 'YARN',
 'B0042TLR2U': 'YARN',
 'B006H7QUJK': 'KNITTING_NEEDLE',
 'B003D7IUT0': 'YARN',
 'B001QG5MH8': 'SKIN_MOISTURIZER',
 'B088BJ7Y62': 'PERSONAL_PILL_DISPENSER',
 'B07SQQMSX8': 'MARKING_PEN',
 'B07P9X4XFF': 'MARKING_PEN',
 'B000SDX54M': 'WINDOW_SHADE',
 'B089SX37W8': 'CARRIER_BAG_CASE',
 'B018CG8J2O': 'HEALTH_PERSONAL_CARE',
 'B01J3L2Z0E': 'SKIN_MOISTURIZER',
 'B01LZAQTKY': 'SKIN_PROTECTANT',
 '0399183647': 'ABIS_BOOK',
 'B083DYHN6K': 'JEWELRY_FINDING',
 'B0013XWDGC': 'BRA',
 'B07D1JRV3V': 'STORAGE_HOOK',
 'B073XRDYF4': 'ADHESIVE_TAPES',
 'B0744CXZD3': 'HAIR_COMB',
 'B07PML3NNN': 'HAIR_CLIP',
 'B071JDFW1L': 'SKIN_MOISTURIZER',
 'B076TRQJ2V': 'HANGING_ROD',
 'B06Y2RZRNG': 'PILLOWCASE',
 'B07LBT8ZZP': 'CURTAIN',
 'B07GL5H78K': 'BUILDING_MATERIAL',
 'B07L6MH96Z': 'FOOD_STORAGE_CONTAINER',
 'B00DW2Z9JK': 'COSMETIC_BRUSH',
 'B07KV65G25': 'MAKE_UP',
 'B00280M13O': 'NUTRITIONAL_SUPPLEMENT',
 'B075NDQP5B': 'NUTRITIONAL_SUPPLEMENT',
 'B07KB8TMS1': 'ITEM_CONTAINER',
 'B084Z2JFDB': 'SKIN_CLEANING_AGENT',
 'B01FRKV5P6': 'TOWEL',
 'B07RTSX4JJ': 'TOWEL',
 'B07L1PHSY9': 'SKIN_CLEANING_AGENT',
 'B07JMQG7LM': 'PANTS',
 'B07TCBQHQ3': 'ASTRINGENT_SUBSTANCE',
 'B08DHLHXWN': 'HUMIDIFIER',
 'B00VADOSJU': 'SKIN_CLEANING_AGENT',
 'B07G36PV11': 'DRESS',
 'B07BXBQ38C': 'FOOD',
 'B07XCYL3GZ': 'TUNIC',
 'B07TSGKR3H': 'APPAREL_GLOVES',
 'B06XYTSHP8': 'SPORT_ACTIVITY_GLOVE',
 'B07QQBCBBL': 'UTILITY_KNIFE',
 'B07XBVRWDY': 'TUNIC',
 'B074D9BSDF': 'ARTIFICIAL_TREE',
 'B000Y52D5G': 'ADHESIVE_TAPES',
 'B089PZD8LZ': 'ART_CRAFT_KIT',
 'B088SP1PC2': 'GIFT_WRAP',
 'B08LMLYNQF': 'TREE_TOPPER',
 'B07DJRFSDF': 'CONSOLE_VIDEO_GAMES',
 '1507211368': 'ABIS_BOOK',
 '0262533359': 'ABIS_BOOK',
 '0738754889': 'CALENDAR',
 'B000KXCKZ0': 'HEALTH_PERSONAL_CARE',
 '1631366734': 'CALENDAR',
 'B008GQUZZK': 'PET_BED_MAT',
 'B07R3W3YPJ': 'GAME_DICE',
 'B01J2RYK8E': 'TABLETOP_GAME',
 'B015E0E3AI': 'HAT',
 'B00G4T5LWI': 'HAT',
 'B083259V7P': 'SHIRT',
 'B01855HOJQ': 'HOME_LIGHTING_AND_LAMPS',
 'B086V1MR47': 'SELF_STICK_NOTE',
 'B07XTDDDPR': 'FACE_SHAPING_MAKEUP',
 'B07P2JYWMQ': 'SWEATER',
 'B071JC2D5G': 'LIP_COLOR',
 'B014S24C4K': 'ABIS_BOOK',
 'B08BW1782Z': 'POWER_CORD',
 'B01LVXODZD': 'UNDERPANTS',
 'B00106TB58': 'PET_FOOD',
 'B00E3UKY18': 'PET_FOOD',
 'B07P9FNMY7': 'BATHWATER_ADDITIVE',
 'B0754MSM7H': 'MEDICATION',
 'B07S9GV83R': 'TOOTHBRUSH',
 'B07PNJQDMY': 'SWEATBAND',
 'B08DNJXPZ2': 'SHORTS',
 'B07SKQBZYN': 'APRON',
 'B08DLNWKFB': 'LINT_REMOVER',
 'B0088X2EVY': 'UNDERPANTS',
 'B07L8ZJNYT': 'FUNNEL',
 'B001F0R7VE': 'VITAMIN',
 'B07QS75JWW': 'GROCERY',
 'B00004YOTJ': 'FABRIC',
 'B07JH2Q7HX': 'THICKENING_AGENT',
 'B07GT4HBMG': 'FRUIT',
 'B07JPJJXQX': 'HERB',
 'B000GCQ8X0': 'MINERAL_SUPPLEMENT',
 '1982113790': 'ABIS_BOOK',
 'B000F4H5GI': 'TEA',
 'B00OLQLS64': 'NUTRITIONAL_SUPPLEMENT',
 'B01HV2A680': 'HERB',
 'B07YFPW8TH': 'SOCKS',
 'B0813YNQ5B': 'HEADPHONES',
 'B074H5ZJZ4': 'BREAD',
 'B089SSMKFN': 'VEGETABLE',
 'B089PMG9LB': 'PACKAGED_SOUP_AND_STEW',
 'B078K4XJR5': 'VEGETABLE',
 'B0787W8XPF': 'FRUIT',
 'B079MH3VQY': 'GROCERY',
 'B074H5B5XG': 'BREAD',
 'B089WHWTN1': 'COOKIE',
 'B07GG84NVR': 'BREAD',
 'B07KV1WMFQ': 'GROCERY',
 'B07FWJ8CQQ': 'FOOD',
 'B074H6X61K': 'SNACK_CHIP_AND_CRISP',
 'B07FX2FL3Z': 'BREAD',
 'B00QWGES8Q': 'OUTDOOR_LIVING',
 'B074F18H4B': 'MEDICATION',
 'B01EKJ941C': 'MEDICATION',
 'B071RSXWGF': 'CURTAIN',
 'B07CZ4K6HX': 'PACKAGED_SOUP_AND_STEW',
 'B088K88DD2': 'FOOD_STORAGE_CONTAINER',
 'B07CV163NL': 'FOOD_STORAGE_CONTAINER',
 'B07PDG2D72': 'HOME',
 'B08M9QHGYW': 'STORAGE_HOOK',
 'B07FZ712QR': 'BREAD',
 'B074J7X1DW': 'CULINARY_SALT',
 'B07QH2N249': 'DAIRY_BASED_CHEESE',
 'B074H58YFZ': 'VEGETABLE',
 'B07FWMNWZY': 'FOOD',
 'B07X3PZ98T': 'EDIBLE_OIL_VEGETABLE',
 'B07QJDHW74': 'PASTRY',
 'B074H5SR5S': 'DAIRY_BASED_DRINK',
 'B07T479YMQ': 'FOOD',
 'B001000IQK': 'FOOD',
 'B01N9676VI': 'FOOD',
 'B07FWNJLQ8': 'BREAD',
 'B000REL6E8': 'SNACK_CHIP_AND_CRISP',
 'B078HTGHH2': 'PACKAGED_SOUP_AND_STEW',
 'B074H51J1K': 'JUICE_AND_JUICE_DRINK',
 'B01J590ALK': 'TEA',
 'B074H67KW3': 'BREAD',
 'B000R7X3JG': 'PACKAGED_SOUP_AND_STEW',
 'B0005ZHALM': 'GROCERY',
 'B07FZ9LFWQ': 'PASTRY',
 'B000SR62ZC': 'TEA',
 'B015MKMSPC': 'MEDICATION',
 'B00HTK1NCS': 'INPUT_MOUSE',
 'B00150LT40': 'NAIL_POLISH',
 'B0814Q7R9X': 'ANIMAL_COLLAR',
 'B085Y7QF2X': 'ANIMAL_HARNESS',
 'B002YIHOVO': 'HERBAL_SUPPLEMENT',
 'B000VOE3QW': 'PET_FOOD',
 'B08LS9STJD': 'THERAPEUTIC_THERMAL_COMPRESS',
 '1539300927': 'ABIS_BOOK',
 'B08L5F6VG4': 'NAIL_TREATMENT',
 'B08N46BVR5': 'ITEM_CONTAINER',
 'B07SHG3Z39': 'LIGHT_BULB',
 'B078TTHTHG': 'JUICE_AND_JUICE_DRINK',
 'B07817RPYF': 'DRINK_FLAVORED',
 'B082WYVJ16': 'DRINK_FLAVORED',
 'B013CIMU9U': 'BRA',
 'B00O2ZU4HS': 'MEDICATION',
 'B07F92YLRW': 'NUTRITIONAL_SUPPLEMENT',
 'B000RWBO7Y': 'BODY_DEODORANT',
 'B08NFJ4GZZ': 'WALLET',
 'B07RRFCN4S': 'PET_SUPPLIES',
 'B07KD7CW5T': 'AMAZON_TABLET',
 'B074VBL8D5': 'DAIRY_BASED_BUTTER',
 'B000QJDZS4': 'DAIRY_BASED_CREAM',
 'B07NFHKJDK': 'BREAKFAST_CEREAL',
 'B078THDYSJ': 'PHYSICAL_MOVIE',
 'B074H6X5KD': 'DAIRY_BASED_CHEESE',
 'B07QJ32TS1': 'TEA',
 'B00JSCOEGC': 'TEA',
 'B079NFKN7T': 'DAIRY_BASED_YOGURT',
 'B07CWZFVVW': 'PASTRY',
 'B07V8VQ3GZ': 'CURTAIN',
 'B077N2N6M6': 'CURTAIN_FASTENER',
 'B074J6X7G8': 'DAIRY_BASED_CHEESE',
 'B074H7L855': 'NOODLE',
 'B07T883TRN': 'SKIN_CLEANING_WIPE',
 'B0785WJ3LT': 'FRUIT',
 'B074H66176': 'SAUCE',
 'B074J5TWN8': 'SAUCE',
 'B08RXS79LJ': 'DISHWARE_BOWL',
 'B082GS6HFH': 'HERBAL_SUPPLEMENT',
 'B07S4D844Y': 'HEALTH_PERSONAL_CARE',
 'B07YX7NHWK': 'SKIN_CLEANING_WIPE',
 'B06XZWG6CV': 'PROTEIN_DRINK',
 'B003QKKVKK': 'PLANTER',
 'B00W4TWHR4': 'BODY_DEODORANT',
 'B01N5336H4': 'MAKEUP_PRIMER',
 'B01MSDLDO1': 'PET_FOOD',
 'B0857LKWKY': 'HAIR_CLEANER_CONDITIONER',
 'B08PPX9VMC': 'BODY_DEODORANT',
 'B075HL9F7H': 'BEAUTY',
 'B086BQ1STX': 'MASSAGER',
 'B07VVQZDL7': 'PET_ACTIVITY_STRUCTURE',
 'B00LN76PC6': 'DAIRY_BASED_CHEESE',
 'B083B3HZNN': 'COOKIE',
 'B074J7QC9F': 'GROCERY',
 'B07YH9GP5K': 'MEAT_ALTERNATIVE',
 'B07QJ32TLK': 'TEA',
 'B074H5H18T': 'BREAD',
 'B074H5J9CM': 'FOOD',
 'B07YHG2VXB': 'FOOD',
 'B08325H8CZ': 'FOOD',
 'B0078DS86U': 'FOOD',
 'B084NJJJQ7': 'CEREAL',
 'B08795KY3J': 'COSMETIC_NAIL_SET',
 'B06XZV7ZGC': 'SKIN_TREATMENT_MASK',
 'B01M5BGAOO': 'NUTRITIONAL_SUPPLEMENT',
 'B005F0OUX8': 'BUILDING_MATERIAL',
 'B07J4498BN': 'BEAUTY',
 'B01CXF7NWM': 'TRASH_CAN',
 'B088RJ6JW9': 'ICE_CUBE_TRAY',
 'B00025K0R6': 'TOOTH_CLEANING_AGENT',
 'B08GV241M5': 'PET_SUPPLIES',
 'B08KT72CRR': 'NAIL_POLISH_REMOVER',
 '1623367417': 'ABIS_BOOK',
 'B07DQB5BCD': 'CONDIMENT',
 'B07FWN3CDK': 'BREAD',
 'B07RL3Y4DY': 'EDIBLE_OIL_VEGETABLE',
 'B085T3DGPD': 'DRINK_FLAVORED',
 'B074VBL8FP': 'SUGAR',
 'B074HJF6QK': 'FOOD',
 'B00MFBVCAO': 'HONEY',
 'B074J9RL65': 'EDIBLE_OIL_VEGETABLE',
 'B089PMF42M': 'LEGUME',
 'B07884NGXV': 'VEGETABLE',
 'B074H6GRTG': 'DAIRY_BASED_CHEESE',
 'B074H6G7GX': 'NOODLE',
 'B074H5SRZX': 'DAIRY_BASED_CHEESE',
 'B07887CXXC': 'VEGETABLE',
 'B074H5BV1K': 'NOODLE',
 'B074VGH1KZ': 'DAIRY_BASED_CHEESE',
 'B074H6R3PL': 'NOODLE',
 'B0899ZXZHK': 'NAIL_DRILL',
 'B07H4FQ44X': 'ANIMAL_CAGE',
 'B07VQLZBNW': 'LIGHT_BULB',
 'B08FT5VXH7': 'LAUNDRY_HAMPER',
 'B07GF66MS8': 'WASTE_BAG',
 'B00HYEUHSU': 'ANIMAL_VITAMIN',
 'B07MH67F17': 'OUTDOOR_LIVING',
 'B0812LP6PJ': 'DAIRY_BASED_CHEESE',
 'B07ZDV17DK': 'LEGUME',
 'B074H6QVKY': 'LEGUME',

In [22]:
data['Category'] = data['ASIN/ISBN (Product Code)'].map(cats_dict)


data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 30 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   Order Date                  1048575 non-null  str
 1   Purchase Price Per Unit     1048575 non-null  float64
 2   Quantity                    1048575 non-null  float64
 3   Shipping Address State      997480 non-null   str
 4   Title                       998235 non-null   str
 5   ASIN/ISBN (Product Code)    1047967 non-null  str
 6   Category                    998470 non-null   str
 7   Survey ResponseID           1048575 non-null  str
 8   Q-demos-age                 1048575 non-null  str
 9   Q-demos-hispanic            1048575 non-null  str
 10  Q-demos-race                1048575 non-null  str
 11  Q-demos-education           1048575 non-null  str
 12  Q-demos-income              1048575 non-null  str
 13  Q-demos-gender              1048575 non-null  str
 14  Q-sexual-orientation        1048575 non-null  str
 15  Q-demos-state               1048575 non-null  str
 16  Q-amazon-use-howmany        1048575 non-null  str
 17  Q-amazon-use-hh-size        1048575 non-null  str
 18  Q-amazon-use-how-oft        1048575 non-null  str
 19  Q-substance-use-cigarettes  1048575 non-null  str
 20  Q-substance-use-marijuana   1048575 non-null  str
 21  Q-substance-use-alcohol     1048575 non-null  str
 22  Q-personal-diabetes         1048575 non-null  str
 23  Q-personal-wheelchair       1048575 non-null  str
 24  Q-life-changes              337784 non-null   str
 25  Q-sell-YOUR-data            1048575 non-null  str
 26  Q-sell-consumer-data        1048575 non-null  str
 27  Q-small-biz-use             1048575 non-null  str
 28  Q-census-use                1048575 non-null  str
 29  Q-research-society          1048575 non-null  str
dtypes: float64(2), str(28)
memory usage: 240.0 MB

In [24]:
# Replacing missing values in Q-life_changes "none" to indicate no life changes selected

data['Q-life-changes'] = data['Q-life-changes'].fillna('None')

In [25]:
data.isnull().sum()

Order Date                        0
Purchase Price Per Unit           0
Quantity                          0
Shipping Address State        51095
Title                         50340
ASIN/ISBN (Product Code)        608
Category                      50105
Survey ResponseID                 0
Q-demos-age                       0
Q-demos-hispanic                  0
Q-demos-race                      0
Q-demos-education                 0
Q-demos-income                    0
Q-demos-gender                    0
Q-sexual-orientation              0
Q-demos-state                     0
Q-amazon-use-howmany              0
Q-amazon-use-hh-size              0
Q-amazon-use-how-oft              0
Q-substance-use-cigarettes        0
Q-substance-use-marijuana         0
Q-substance-use-alcohol           0
Q-personal-diabetes               0
Q-personal-wheelchair             0
Q-life-changes                    0
Q-sell-YOUR-data                  0
Q-sell-consumer-data              0
Q-small-biz-use                   0
Q-census-use                      0
Q-research-society                0
dtype: int64

In [27]:
# Removing the remaining rows where missing values are present
data = data.dropna()

In [29]:
# data.isnull().sum()

In [30]:
data.columns

Index(['Order Date', 'Purchase Price Per Unit', 'Quantity',
       'Shipping Address State', 'Title', 'ASIN/ISBN (Product Code)',
       'Category', 'Survey ResponseID', 'Q-demos-age', 'Q-demos-hispanic',
       'Q-demos-race', 'Q-demos-education', 'Q-demos-income', 'Q-demos-gender',
       'Q-sexual-orientation', 'Q-demos-state', 'Q-amazon-use-howmany',
       'Q-amazon-use-hh-size', 'Q-amazon-use-how-oft',
       'Q-substance-use-cigarettes', 'Q-substance-use-marijuana',
       'Q-substance-use-alcohol', 'Q-personal-diabetes',
       'Q-personal-wheelchair', 'Q-life-changes', 'Q-sell-YOUR-data',
       'Q-sell-consumer-data', 'Q-small-biz-use', 'Q-census-use',
       'Q-research-society'],
      dtype='str')

In [41]:
# removing redundant information from column names
# removing the "Q-" first, then removing the remaining redundant words
data.columns = data.columns.str.replace('Q-', '')\
    .str.replace('demos-', '')\
    .str.replace('amazon-use-', '')\
    .str.replace('substance-use-', '')\
    .str.replace('personal-', '')
data.columns

Index(['Order Date', 'Purchase Price Per Unit', 'Quantity',
       'Shipping Address State', 'Title', 'ASIN/ISBN (Product Code)',
       'Category', 'Survey ResponseID', 'age', 'hispanic', 'race', 'education',
       'income', 'gender', 'sexual-orientation', 'state', 'howmany', 'hh-size',
       'how-oft', 'cigarettes', 'marijuana', 'alcohol', 'diabetes',
       'wheelchair', 'life-changes', 'sell-YOUR-data', 'sell-consumer-data',
       'small-biz-use', 'census-use', 'research-society'],
      dtype='str')

In [46]:
data.info()

<class 'pandas.DataFrame'>
Index: 948676 entries, 0 to 1048574
Data columns (total 30 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Order Date                948676 non-null  str
 1   Purchase Price Per Unit   948676 non-null  float64
 2   Quantity                  948676 non-null  float64
 3   Shipping Address State    948676 non-null  str
 4   Title                     948676 non-null  str
 5   ASIN/ISBN (Product Code)  948676 non-null  str
 6   Category                  948676 non-null  str
 7   Survey ResponseID         948676 non-null  str
 8   age                       948676 non-null  str
 9   hispanic                  948676 non-null  str
 10  race                      948676 non-null  str
 11  education                 948676 non-null  str
 12  income                    948676 non-null  str
 13  gender                    948676 non-null  str
 14  sexual-orientation        948676 non-null  str
 15  state                     948676 non-null  str
 16  howmany                   948676 non-null  str
 17  hh-size                   948676 non-null  str
 18  how-oft                   948676 non-null  str
 19  cigarettes                948676 non-null  str
 20  marijuana                 948676 non-null  str
 21  alcohol                   948676 non-null  str
 22  diabetes                  948676 non-null  str
 23  wheelchair                948676 non-null  str
 24  life-changes              948676 non-null  str
 25  sell-YOUR-data            948676 non-null  str
 26  sell-consumer-data        948676 non-null  str
 27  small-biz-use             948676 non-null  str
 28  census-use                948676 non-null  str
 29  research-society          948676 non-null  str
dtypes: float64(2), str(28)
memory usage: 224.4 MB